/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.idraGroup.lavadero.view;

/**
 *
 * @author emmae
 */
public class ClienteView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteView.class.getName());

    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clienteTabbedPanel = new javax.swing.JTabbedPane();
        clienteCrearPanel = new javax.swing.JPanel();
        bgClienteCrear = new javax.swing.JPanel();
        clienteSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        clienteCrearTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        separatorNombre = new javax.swing.JSeparator();
        labelDni = new javax.swing.JLabel();
        inputDni = new javax.swing.JTextField();
        separatorDni = new javax.swing.JSeparator();
        labelTelefono = new javax.swing.JLabel();
        inputTelefono = new javax.swing.JTextField();
        separatorTelefono = new javax.swing.JSeparator();
        botonGuardarCliente = new javax.swing.JButton();
        clienteActualizarPanel = new javax.swing.JPanel();
        bgClienteCrear1 = new javax.swing.JPanel();
        clienteSiluetaImg1 = new javax.swing.JLabel();
        CiudadImg1 = new javax.swing.JLabel();
        LogoImg1 = new javax.swing.JLabel();
        clienteCrearTitulo1 = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        inputNombre1 = new javax.swing.JTextField();
        separatorNombre1 = new javax.swing.JSeparator();
        labelDni1 = new javax.swing.JLabel();
        inputDni1 = new javax.swing.JTextField();
        separatorDni1 = new javax.swing.JSeparator();
        labelTelefono1 = new javax.swing.JLabel();
        inputTelefono1 = new javax.swing.JTextField();
        separatorTelefono1 = new javax.swing.JSeparator();
        botonGuardarCliente1 = new javax.swing.JButton();
        clienteBorrarPanel = new javax.swing.JPanel();
        bgClienteCrear2 = new javax.swing.JPanel();
        clienteSiluetaImg2 = new javax.swing.JLabel();
        CiudadImg2 = new javax.swing.JLabel();
        LogoImg2 = new javax.swing.JLabel();
        clienteCrearTitulo2 = new javax.swing.JLabel();
        labelNombre2 = new javax.swing.JLabel();
        inputNombre2 = new javax.swing.JTextField();
        separatorDni2 = new javax.swing.JSeparator();
        botonGuardarCliente2 = new javax.swing.JButton();
        clienteListarPanel = new javax.swing.JPanel();
        bgClienteCrear3 = new javax.swing.JPanel();
        clienteSiluetaImg3 = new javax.swing.JLabel();
        CiudadImg3 = new javax.swing.JLabel();
        LogoImg3 = new javax.swing.JLabel();
        clienteCrearTitulo3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clienteTabbedPanel.setBackground(new java.awt.Color(255, 255, 255));
        clienteTabbedPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clienteTabbedPanel.setForeground(new java.awt.Color(0, 51, 51));
        clienteTabbedPanel.setToolTipText("");

        bgClienteCrear.setBackground(new java.awt.Color(255, 255, 255));
        bgClienteCrear.setForeground(new java.awt.Color(255, 255, 255));
        bgClienteCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        bgClienteCrear.add(clienteSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        bgClienteCrear.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        bgClienteCrear.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 40));

        clienteCrearTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        clienteCrearTitulo.setText("REGISTRAR USUARIO");
        bgClienteCrear.add(clienteCrearTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, 30));

        labelNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelNombre.setText("DNI");
        bgClienteCrear.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        inputNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputNombre.setForeground(new java.awt.Color(204, 204, 204));
        inputNombre.setText("Ingrese su numero de documento");
        inputNombre.setBorder(null);
        inputNombre.setCaretColor(new java.awt.Color(204, 204, 204));
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        bgClienteCrear.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 390, -1));

        separatorNombre.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear.add(separatorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, -1));

        labelDni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelDni.setText("NOMBRE");
        bgClienteCrear.add(labelDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        inputDni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputDni.setForeground(new java.awt.Color(204, 204, 204));
        inputDni.setText("Ingrese su nombre");
        inputDni.setBorder(null);
        inputDni.setCaretColor(new java.awt.Color(204, 204, 204));
        inputDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDniActionPerformed(evt);
            }
        });
        bgClienteCrear.add(inputDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 390, -1));

        separatorDni.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear.add(separatorDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, -1));

        labelTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelTelefono.setText("TELEFONO");
        bgClienteCrear.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        inputTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputTelefono.setForeground(new java.awt.Color(204, 204, 204));
        inputTelefono.setText("Ingrese su numero de telefono");
        inputTelefono.setBorder(null);
        inputTelefono.setCaretColor(new java.awt.Color(204, 204, 204));
        inputTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefonoActionPerformed(evt);
            }
        });
        bgClienteCrear.add(inputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 390, -1));

        separatorTelefono.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear.add(separatorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 340, -1));

        botonGuardarCliente.setBackground(new java.awt.Color(0, 134, 190));
        botonGuardarCliente.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarCliente.setText("Guardar");
        botonGuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bgClienteCrear.add(botonGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        javax.swing.GroupLayout clienteCrearPanelLayout = new javax.swing.GroupLayout(clienteCrearPanel);
        clienteCrearPanel.setLayout(clienteCrearPanelLayout);
        clienteCrearPanelLayout.setHorizontalGroup(
            clienteCrearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgClienteCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        clienteCrearPanelLayout.setVerticalGroup(
            clienteCrearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteCrearPanelLayout.createSequentialGroup()
                .addComponent(bgClienteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        clienteTabbedPanel.addTab("CREAR", clienteCrearPanel);

        bgClienteCrear1.setBackground(new java.awt.Color(255, 255, 255));
        bgClienteCrear1.setForeground(new java.awt.Color(255, 255, 255));
        bgClienteCrear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        bgClienteCrear1.add(clienteSiluetaImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        CiudadImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        bgClienteCrear1.add(CiudadImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        bgClienteCrear1.add(LogoImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 40));

        clienteCrearTitulo1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        clienteCrearTitulo1.setText("ACTUALIZAR USUARIO");
        bgClienteCrear1.add(clienteCrearTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, 30));

        labelNombre1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelNombre1.setText("DNI");
        bgClienteCrear1.add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        inputNombre1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputNombre1.setForeground(new java.awt.Color(204, 204, 204));
        inputNombre1.setText("Ingrese su numero de documento");
        inputNombre1.setBorder(null);
        inputNombre1.setCaretColor(new java.awt.Color(204, 204, 204));
        inputNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre1ActionPerformed(evt);
            }
        });
        bgClienteCrear1.add(inputNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 390, -1));

        separatorNombre1.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear1.add(separatorNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, -1));

        labelDni1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelDni1.setText("NOMBRE");
        bgClienteCrear1.add(labelDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        inputDni1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputDni1.setForeground(new java.awt.Color(204, 204, 204));
        inputDni1.setText("Ingrese su nombre");
        inputDni1.setBorder(null);
        inputDni1.setCaretColor(new java.awt.Color(204, 204, 204));
        inputDni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDni1ActionPerformed(evt);
            }
        });
        bgClienteCrear1.add(inputDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 390, -1));

        separatorDni1.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear1.add(separatorDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, -1));

        labelTelefono1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelTelefono1.setText("TELEFONO");
        bgClienteCrear1.add(labelTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        inputTelefono1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputTelefono1.setForeground(new java.awt.Color(204, 204, 204));
        inputTelefono1.setText("Ingrese su numero de telefono");
        inputTelefono1.setBorder(null);
        inputTelefono1.setCaretColor(new java.awt.Color(204, 204, 204));
        inputTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefono1ActionPerformed(evt);
            }
        });
        bgClienteCrear1.add(inputTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 390, -1));

        separatorTelefono1.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear1.add(separatorTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 340, -1));

        botonGuardarCliente1.setBackground(new java.awt.Color(0, 134, 190));
        botonGuardarCliente1.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonGuardarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarCliente1.setText("Guardar");
        botonGuardarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bgClienteCrear1.add(botonGuardarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        javax.swing.GroupLayout clienteActualizarPanelLayout = new javax.swing.GroupLayout(clienteActualizarPanel);
        clienteActualizarPanel.setLayout(clienteActualizarPanelLayout);
        clienteActualizarPanelLayout.setHorizontalGroup(
            clienteActualizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgClienteCrear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        clienteActualizarPanelLayout.setVerticalGroup(
            clienteActualizarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteActualizarPanelLayout.createSequentialGroup()
                .addComponent(bgClienteCrear1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        clienteTabbedPanel.addTab("ACTUALIZAR", clienteActualizarPanel);

        bgClienteCrear2.setBackground(new java.awt.Color(255, 255, 255));
        bgClienteCrear2.setForeground(new java.awt.Color(255, 255, 255));
        bgClienteCrear2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        bgClienteCrear2.add(clienteSiluetaImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        CiudadImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        bgClienteCrear2.add(CiudadImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        bgClienteCrear2.add(LogoImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 40));

        clienteCrearTitulo2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        clienteCrearTitulo2.setText("ELIMINAR USUARIO");
        bgClienteCrear2.add(clienteCrearTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 30));

        labelNombre2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelNombre2.setText("DNI");
        bgClienteCrear2.add(labelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        inputNombre2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputNombre2.setForeground(new java.awt.Color(204, 204, 204));
        inputNombre2.setText("Ingrese el documento del usuario a eliminar.");
        inputNombre2.setBorder(null);
        inputNombre2.setCaretColor(new java.awt.Color(204, 204, 204));
        inputNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre2ActionPerformed(evt);
            }
        });
        bgClienteCrear2.add(inputNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 390, -1));

        separatorDni2.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear2.add(separatorDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, -1));

        botonGuardarCliente2.setBackground(new java.awt.Color(153, 0, 0));
        botonGuardarCliente2.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonGuardarCliente2.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarCliente2.setText("Eliminar");
        botonGuardarCliente2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bgClienteCrear2.add(botonGuardarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        javax.swing.GroupLayout clienteBorrarPanelLayout = new javax.swing.GroupLayout(clienteBorrarPanel);
        clienteBorrarPanel.setLayout(clienteBorrarPanelLayout);
        clienteBorrarPanelLayout.setHorizontalGroup(
            clienteBorrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgClienteCrear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        clienteBorrarPanelLayout.setVerticalGroup(
            clienteBorrarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteBorrarPanelLayout.createSequentialGroup()
                .addComponent(bgClienteCrear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        clienteTabbedPanel.addTab("BORRAR", clienteBorrarPanel);

        bgClienteCrear3.setBackground(new java.awt.Color(255, 255, 255));
        bgClienteCrear3.setForeground(new java.awt.Color(255, 255, 255));
        bgClienteCrear3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        bgClienteCrear3.add(clienteSiluetaImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        CiudadImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        bgClienteCrear3.add(CiudadImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        bgClienteCrear3.add(LogoImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        clienteCrearTitulo3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        clienteCrearTitulo3.setText("LISTA DE USUARIO");
        bgClienteCrear3.add(clienteCrearTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 280, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Emmanul", "45500223", "2236202637"},
                {"2", "Lorenzo", "46879458", "2234587889"},
                {"3", "Iñaki", "45121452", "2231234567"}
            },
            new String [] {
                "ID", "NOMBRE", "DNI", "TELEFONO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bgClienteCrear3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 470, 370));

        javax.swing.GroupLayout clienteListarPanelLayout = new javax.swing.GroupLayout(clienteListarPanel);
        clienteListarPanel.setLayout(clienteListarPanelLayout);
        clienteListarPanelLayout.setHorizontalGroup(
            clienteListarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgClienteCrear3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        clienteListarPanelLayout.setVerticalGroup(
            clienteListarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clienteListarPanelLayout.createSequentialGroup()
                .addComponent(bgClienteCrear3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        clienteTabbedPanel.addTab("LISTAR", clienteListarPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clienteTabbedPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clienteTabbedPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefonoActionPerformed

    private void inputDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDniActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre1ActionPerformed

    private void inputDni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDni1ActionPerformed

    private void inputTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefono1ActionPerformed

    private void inputNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.JLabel CiudadImg1;
    private javax.swing.JLabel CiudadImg2;
    private javax.swing.JLabel CiudadImg3;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JLabel LogoImg1;
    private javax.swing.JLabel LogoImg2;
    private javax.swing.JLabel LogoImg3;
    private javax.swing.JPanel bgClienteCrear;
    private javax.swing.JPanel bgClienteCrear1;
    private javax.swing.JPanel bgClienteCrear2;
    private javax.swing.JPanel bgClienteCrear3;
    private javax.swing.JButton botonGuardarCliente;
    private javax.swing.JButton botonGuardarCliente1;
    private javax.swing.JButton botonGuardarCliente2;
    private javax.swing.JPanel clienteActualizarPanel;
    private javax.swing.JPanel clienteBorrarPanel;
    private javax.swing.JPanel clienteCrearPanel;
    private javax.swing.JLabel clienteCrearTitulo;
    private javax.swing.JLabel clienteCrearTitulo1;
    private javax.swing.JLabel clienteCrearTitulo2;
    private javax.swing.JLabel clienteCrearTitulo3;
    private javax.swing.JPanel clienteListarPanel;
    private javax.swing.JLabel clienteSiluetaImg;
    private javax.swing.JLabel clienteSiluetaImg1;
    private javax.swing.JLabel clienteSiluetaImg2;
    private javax.swing.JLabel clienteSiluetaImg3;
    private javax.swing.JTabbedPane clienteTabbedPanel;
    private javax.swing.JTextField inputDni;
    private javax.swing.JTextField inputDni1;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNombre1;
    private javax.swing.JTextField inputNombre2;
    private javax.swing.JTextField inputTelefono;
    private javax.swing.JTextField inputTelefono1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelDni1;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTelefono1;
    private javax.swing.JSeparator separatorDni;
    private javax.swing.JSeparator separatorDni1;
    private javax.swing.JSeparator separatorDni2;
    private javax.swing.JSeparator separatorNombre;
    private javax.swing.JSeparator separatorNombre1;
    private javax.swing.JSeparator separatorTelefono;
    private javax.swing.JSeparator separatorTelefono1;
    // End of variables declaration//GEN-END:variables
}
