/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.cliente;

import com.idraGroup.lavadero.controller.ClienteController;

/**
 *
 * @author LoloColombo
 */
public class ClienteView extends javax.swing.JPanel {


    private final ClienteController clienteController;
    private final PanelListarCliente panelListarCliente;
    public ClienteView(ClienteController clienteController) {
        initComponents();
        this.clienteController = clienteController;
        this.panelListarCliente = new PanelListarCliente(clienteController);
        
        PanelAgregarCliente panelAgregarCliente = new PanelAgregarCliente(clienteController, panelListarCliente);
        tabbedPaneCliente.addTab("CREAR",panelAgregarCliente);
        
        PanelActualizarCliente panelActualizarCliente = new PanelActualizarCliente(clienteController, panelListarCliente);
        tabbedPaneCliente.addTab("ACTUALIZAR",panelActualizarCliente);
        
        PanelEliminarCliente panelEliminarCliente = new PanelEliminarCliente(clienteController, panelListarCliente);
        tabbedPaneCliente.addTab("ELIMINAR",panelEliminarCliente);
        
        tabbedPaneCliente.addTab("LISTAR",panelListarCliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneCliente = new com.idraGroup.lavadero.view.ravenTabbed.TabbedPaneCustom();

        setBackground(new java.awt.Color(255, 255, 255));

        tabbedPaneCliente.setSelectedColor(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.idraGroup.lavadero.view.ravenTabbed.TabbedPaneCustom tabbedPaneCliente;
    // End of variables declaration//GEN-END:variables
}
