/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.cliente;

/**
 *
 * @author LoloColombo
 */
public class PanelActualizarCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelActualizarCliente
     */
    public PanelActualizarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlActualizarCliente = new javax.swing.JPanel();
        clienteSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDniActual = new javax.swing.JLabel();
        separatorNombre = new javax.swing.JSeparator();
        lblNuevoNombre = new javax.swing.JLabel();
        separatorDni = new javax.swing.JSeparator();
        lblNuevoTelefono = new javax.swing.JLabel();
        separatorDniActual = new javax.swing.JSeparator();
        botonActualizarCliente = new javax.swing.JButton();
        lblNuevoDni = new javax.swing.JLabel();
        separatorTelefono = new javax.swing.JSeparator();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();

        pnlActualizarCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        pnlActualizarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        pnlActualizarCliente.add(clienteSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 300, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlActualizarCliente.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 300, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlActualizarCliente.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("ACTUALIZAR USUARIO");
        pnlActualizarCliente.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 280, 30));

        lblDniActual.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblDniActual.setText("DNI ACTUAL");
        pnlActualizarCliente.add(lblDniActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        separatorNombre.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarCliente.add(separatorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 340, 10));

        lblNuevoNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoNombre.setText("NUEVO NOMBRE");
        pnlActualizarCliente.add(lblNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        separatorDni.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarCliente.add(separatorDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, 10));

        lblNuevoTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoTelefono.setText("NUEVO TELEFONO");
        pnlActualizarCliente.add(lblNuevoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        separatorDniActual.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarCliente.add(separatorDniActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 10));

        botonActualizarCliente.setBackground(new java.awt.Color(0, 134, 190));
        botonActualizarCliente.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarCliente.setText("Guardar");
        botonActualizarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlActualizarCliente.add(botonActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        lblNuevoDni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoDni.setText("NUEVO DNI");
        pnlActualizarCliente.add(lblNuevoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        separatorTelefono.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarCliente.add(separatorTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 340, 10));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarCliente.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 340, -1));

        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarCliente.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 340, -1));

        try {
            jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarCliente.add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, -1));
        pnlActualizarCliente.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JButton botonActualizarCliente;
    private javax.swing.JLabel clienteSiluetaImg;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblDniActual;
    private javax.swing.JLabel lblNuevoDni;
    private javax.swing.JLabel lblNuevoNombre;
    private javax.swing.JLabel lblNuevoTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlActualizarCliente;
    private javax.swing.JSeparator separatorDni;
    private javax.swing.JSeparator separatorDniActual;
    private javax.swing.JSeparator separatorNombre;
    private javax.swing.JSeparator separatorTelefono;
    // End of variables declaration//GEN-END:variables
}
