/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.cliente;

import com.idraGroup.lavadero.controller.ClienteController;
import com.idraGroup.lavadero.model.Cliente;
import java.util.Optional;
import javax.swing.JOptionPane;

/**
 *
 * @author LoloColombo
 */
public class PanelActualizarCliente extends javax.swing.JPanel {

    private final ClienteController clienteController;
    private final PanelListarCliente panelListarCliente;
    private Cliente clienteEnEdicion;

    public PanelActualizarCliente(ClienteController clienteController, PanelListarCliente panelListarCliente) {
        this.clienteController = clienteController;
        this.panelListarCliente = panelListarCliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlActualizarCliente = new javax.swing.JPanel();
        clienteSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDniActual = new javax.swing.JLabel();
        lblNuevoNombre = new javax.swing.JLabel();
        lblNuevoTelefono = new javax.swing.JLabel();
        botonActualizarCliente = new javax.swing.JButton();
        lblNuevoDni = new javax.swing.JLabel();
        inputNuevoDni = new javax.swing.JFormattedTextField();
        inputNuevoTelefono = new javax.swing.JFormattedTextField();
        inputDniActual = new javax.swing.JFormattedTextField();
        inputNuevoNombre = new javax.swing.JTextField();

        pnlActualizarCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        pnlActualizarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        pnlActualizarCliente.add(clienteSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 300, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlActualizarCliente.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 300, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlActualizarCliente.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("ACTUALIZAR USUARIO");
        pnlActualizarCliente.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 280, 30));

        lblDniActual.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblDniActual.setText("DNI ACTUAL");
        pnlActualizarCliente.add(lblDniActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblNuevoNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoNombre.setText("NUEVO NOMBRE");
        pnlActualizarCliente.add(lblNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblNuevoTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoTelefono.setText("NUEVO TELEFONO");
        pnlActualizarCliente.add(lblNuevoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        botonActualizarCliente.setBackground(new java.awt.Color(0, 134, 190));
        botonActualizarCliente.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonActualizarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarCliente.setText("Guardar");
        botonActualizarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
/**
 * actionPerformed.
 * @param evt java.awt.event.ActionEvent.

 */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarClienteActionPerformed(evt);
            }
        });
        pnlActualizarCliente.add(botonActualizarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        lblNuevoDni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoDni.setText("NUEVO DNI");
        pnlActualizarCliente.add(lblNuevoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        try {
            inputNuevoDni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarCliente.add(inputNuevoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 340, -1));

        try {
            inputNuevoTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarCliente.add(inputNuevoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 340, -1));

        try {
            inputDniActual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarCliente.add(inputDniActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, -1));
        pnlActualizarCliente.add(inputNuevoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarClienteActionPerformed
        try {
            String dniABuscar = inputDniActual.getText().trim();

            String nuevoNombre = inputNuevoNombre.getText().trim();
            String nuevoDni = inputNuevoDni.getText().trim();
            String nuevoTelefono = inputNuevoTelefono.getText().trim();

            if (dniABuscar.isEmpty()) {
                throw new IllegalArgumentException("Ingrese el DNI ACTUAL del cliente que desea modificar.");
            }
            if (nuevoDni.isEmpty()) {
                throw new IllegalArgumentException("El nuevo DNI no puede estar vacío.");
            }
            if (nuevoNombre.isEmpty()) {
                throw new IllegalArgumentException("El nuevo nombre no puede estar vacío.");
            }
            if (nuevoTelefono.isEmpty()) {
                throw new IllegalArgumentException("El nuevo telefono no puede estar vacío.");
            }

            Optional<Cliente> resultado = clienteController.buscarPorDni(dniABuscar);

            if (resultado.isPresent()) {
                this.clienteEnEdicion = resultado.get();

                this.clienteEnEdicion.setNombre(nuevoNombre);
                this.clienteEnEdicion.setDni(nuevoDni);
                this.clienteEnEdicion.setTelefono(nuevoTelefono);

                clienteController.actualizarCliente(this.clienteEnEdicion);

                JOptionPane.showMessageDialog(this, "Cliente (DNI: " + dniABuscar + ") actualizado a " + nuevoDni + " exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                LimpiarInputs();

                panelListarCliente.recargarDatos();

            } else {
                JOptionPane.showMessageDialog(this,
                        "No se encontró un cliente con el Dni: " + dniABuscar + ". No se realizó la actualización.",
                        "Advertencia",
                        JOptionPane.WARNING_MESSAGE);
                LimpiarInputs();
            }

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Validación", JOptionPane.WARNING_MESSAGE);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: DNI duplicado o error de DB. " + e.getMessage(), "Error de persistencia", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonActualizarClienteActionPerformed

    private void LimpiarInputs() {
        inputDniActual.setText("");
        inputDniActual.setValue(null);
        inputNuevoDni.setText("");
        inputNuevoDni.setValue(null);
        inputNuevoTelefono.setText("");
        inputNuevoTelefono.setValue(null);
        inputNuevoNombre.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JButton botonActualizarCliente;
    private javax.swing.JLabel clienteSiluetaImg;
    private javax.swing.JFormattedTextField inputDniActual;
    private javax.swing.JFormattedTextField inputNuevoDni;
    private javax.swing.JTextField inputNuevoNombre;
    private javax.swing.JFormattedTextField inputNuevoTelefono;
    private javax.swing.JLabel lblDniActual;
    private javax.swing.JLabel lblNuevoDni;
    private javax.swing.JLabel lblNuevoNombre;
    private javax.swing.JLabel lblNuevoTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlActualizarCliente;
    // End of variables declaration//GEN-END:variables

}
