/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.cliente;

/**
 *
 * @author LoloColombo
 */
public class PanelEliminarCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelEliminarCliente
     */
    public PanelEliminarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEliminarCliente = new javax.swing.JPanel();
        clienteSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDniEliminar = new javax.swing.JLabel();
        inputDniEliminar = new javax.swing.JTextField();
        separatorDni = new javax.swing.JSeparator();
        botonEliminarCliente = new javax.swing.JButton();

        pnlEliminarCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        pnlEliminarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        pnlEliminarCliente.add(clienteSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlEliminarCliente.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlEliminarCliente.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("ELIMINAR USUARIO");
        pnlEliminarCliente.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 30));

        lblDniEliminar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblDniEliminar.setText("DNI");
        pnlEliminarCliente.add(lblDniEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        inputDniEliminar.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputDniEliminar.setForeground(new java.awt.Color(204, 204, 204));
        inputDniEliminar.setText("Ingrese el documento del usuario a eliminar.");
        inputDniEliminar.setBorder(null);
        inputDniEliminar.setCaretColor(new java.awt.Color(204, 204, 204));
        inputDniEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDniEliminarActionPerformed(evt);
            }
        });
        pnlEliminarCliente.add(inputDniEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 390, -1));

        separatorDni.setForeground(new java.awt.Color(0, 0, 0));
        pnlEliminarCliente.add(separatorDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, -1));

        botonEliminarCliente.setBackground(new java.awt.Color(153, 0, 0));
        botonEliminarCliente.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarCliente.setText("Eliminar");
        botonEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEliminarCliente.add(botonEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputDniEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDniEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDniEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JLabel clienteSiluetaImg;
    private javax.swing.JTextField inputDniEliminar;
    private javax.swing.JLabel lblDniEliminar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlEliminarCliente;
    private javax.swing.JSeparator separatorDni;
    // End of variables declaration//GEN-END:variables
}
