/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.cliente;

/**
 *
 * @author LoloColombo
 */
public class PanelActualizarCliente extends javax.swing.JPanel {

    /**
     * Creates new form PanelActualizarCliente
     */
    public PanelActualizarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgClienteCrear1 = new javax.swing.JPanel();
        clienteSiluetaImg1 = new javax.swing.JLabel();
        CiudadImg1 = new javax.swing.JLabel();
        LogoImg1 = new javax.swing.JLabel();
        clienteCrearTitulo1 = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        inputNombre1 = new javax.swing.JTextField();
        separatorNombre1 = new javax.swing.JSeparator();
        labelDni1 = new javax.swing.JLabel();
        inputDni1 = new javax.swing.JTextField();
        separatorDni1 = new javax.swing.JSeparator();
        labelTelefono1 = new javax.swing.JLabel();
        inputTelefono1 = new javax.swing.JTextField();
        separatorTelefono1 = new javax.swing.JSeparator();
        botonGuardarCliente1 = new javax.swing.JButton();
        labelNombre2 = new javax.swing.JLabel();
        inputNombre2 = new javax.swing.JTextField();
        separatorTelefono2 = new javax.swing.JSeparator();

        bgClienteCrear1.setBackground(new java.awt.Color(255, 255, 255));
        bgClienteCrear1.setForeground(new java.awt.Color(255, 255, 255));
        bgClienteCrear1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        bgClienteCrear1.add(clienteSiluetaImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 290, 250));

        CiudadImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        bgClienteCrear1.add(CiudadImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 300, 430));

        LogoImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        bgClienteCrear1.add(LogoImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 40));

        clienteCrearTitulo1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        clienteCrearTitulo1.setText("ACTUALIZAR USUARIO");
        bgClienteCrear1.add(clienteCrearTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 280, 30));

        labelNombre1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelNombre1.setText("DNI ACTUAL");
        bgClienteCrear1.add(labelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        inputNombre1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputNombre1.setForeground(new java.awt.Color(204, 204, 204));
        inputNombre1.setText("Ingrese su numero de documento");
        inputNombre1.setBorder(null);
        inputNombre1.setCaretColor(new java.awt.Color(204, 204, 204));
        inputNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre1ActionPerformed(evt);
            }
        });
        bgClienteCrear1.add(inputNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 390, -1));

        separatorNombre1.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear1.add(separatorNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 340, 10));

        labelDni1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelDni1.setText("NUEVO NOMBRE");
        bgClienteCrear1.add(labelDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        inputDni1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputDni1.setForeground(new java.awt.Color(204, 204, 204));
        inputDni1.setText("Ingrese su nombre");
        inputDni1.setBorder(null);
        inputDni1.setCaretColor(new java.awt.Color(204, 204, 204));
        inputDni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDni1ActionPerformed(evt);
            }
        });
        bgClienteCrear1.add(inputDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 390, -1));

        separatorDni1.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear1.add(separatorDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, 10));

        labelTelefono1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelTelefono1.setText("NUEVO TELEFONO");
        bgClienteCrear1.add(labelTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        inputTelefono1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputTelefono1.setForeground(new java.awt.Color(204, 204, 204));
        inputTelefono1.setText("Ingrese su numero de telefono");
        inputTelefono1.setBorder(null);
        inputTelefono1.setCaretColor(new java.awt.Color(204, 204, 204));
        inputTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefono1ActionPerformed(evt);
            }
        });
        bgClienteCrear1.add(inputTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 390, -1));

        separatorTelefono1.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear1.add(separatorTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 10));

        botonGuardarCliente1.setBackground(new java.awt.Color(0, 134, 190));
        botonGuardarCliente1.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonGuardarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarCliente1.setText("Guardar");
        botonGuardarCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bgClienteCrear1.add(botonGuardarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        labelNombre2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelNombre2.setText("NUEVO DNI");
        bgClienteCrear1.add(labelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        inputNombre2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputNombre2.setForeground(new java.awt.Color(204, 204, 204));
        inputNombre2.setText("Ingrese su numero de documento");
        inputNombre2.setBorder(null);
        inputNombre2.setCaretColor(new java.awt.Color(204, 204, 204));
        inputNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre2ActionPerformed(evt);
            }
        });
        bgClienteCrear1.add(inputNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 390, -1));

        separatorTelefono2.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear1.add(separatorTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 340, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bgClienteCrear1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgClienteCrear1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre1ActionPerformed

    private void inputDni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDni1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDni1ActionPerformed

    private void inputTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTelefono1ActionPerformed

    private void inputNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg1;
    private javax.swing.JLabel LogoImg1;
    private javax.swing.JPanel bgClienteCrear1;
    private javax.swing.JButton botonGuardarCliente1;
    private javax.swing.JLabel clienteCrearTitulo1;
    private javax.swing.JLabel clienteSiluetaImg1;
    private javax.swing.JTextField inputDni1;
    private javax.swing.JTextField inputNombre1;
    private javax.swing.JTextField inputNombre2;
    private javax.swing.JTextField inputTelefono1;
    private javax.swing.JLabel labelDni1;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelTelefono1;
    private javax.swing.JSeparator separatorDni1;
    private javax.swing.JSeparator separatorNombre1;
    private javax.swing.JSeparator separatorTelefono1;
    private javax.swing.JSeparator separatorTelefono2;
    // End of variables declaration//GEN-END:variables
}
