/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.cliente;

import com.idraGroup.lavadero.controller.ClienteController;
import com.idraGroup.lavadero.model.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author LoloColombo
 */
public class PanelAgregarCliente extends javax.swing.JPanel {

    private final ClienteController clienteController;
    private final PanelListarCliente panelListarCliente;

    public PanelAgregarCliente(ClienteController clienteController, PanelListarCliente panelListarCliente) {
        this.clienteController = clienteController;
        this.panelListarCliente = panelListarCliente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAgregarCliente = new javax.swing.JPanel();
        clienteSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        botonGuardarCliente = new javax.swing.JButton();
        inputDni = new javax.swing.JFormattedTextField();
        inputNombre = new javax.swing.JTextField();
        inputTelefono = new javax.swing.JFormattedTextField();

        pnlAgregarCliente.setBackground(new java.awt.Color(255, 255, 255));
        pnlAgregarCliente.setForeground(new java.awt.Color(255, 255, 255));
        pnlAgregarCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clienteSilueta.png"))); // NOI18N
        pnlAgregarCliente.add(clienteSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlAgregarCliente.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlAgregarCliente.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("REGISTRAR USUARIO");
        pnlAgregarCliente.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, 30));

        lblDni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblDni.setText("DNI");
        pnlAgregarCliente.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblNombre.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNombre.setText("NOMBRE");
        pnlAgregarCliente.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelTelefono.setText("TELEFONO");
        pnlAgregarCliente.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        botonGuardarCliente.setBackground(new java.awt.Color(0, 134, 190));
        botonGuardarCliente.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonGuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarCliente.setText("Guardar");
        botonGuardarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarClienteActionPerformed(evt);
            }
        });
        pnlAgregarCliente.add(botonGuardarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        try {
            inputDni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlAgregarCliente.add(inputDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 340, -1));
        pnlAgregarCliente.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 340, -1));

        try {
            inputTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlAgregarCliente.add(inputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgregarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarClienteActionPerformed
        try {
            String nombre = inputNombre.getText();
            String dni = inputDni.getText();
            String telefono = inputTelefono.getText();

            if (nombre.isEmpty()) {
                throw new IllegalArgumentException("El nombre es un campo obligatorio");
            }
            if (dni.isEmpty()) {
                throw new IllegalArgumentException("El DNI es un campo obligatorio");
            }

            if (telefono.isEmpty()) {
                throw new IllegalArgumentException("El telefono es un campo obligatorio");
            }

            Cliente nuevoCliente = new Cliente();
            nuevoCliente.setNombre(nombre);
            nuevoCliente.setDni(dni);
            nuevoCliente.setTelefono(telefono);

            Cliente clienteGuardado = clienteController.crearCliente(nuevoCliente);
            JOptionPane.showMessageDialog(this, "Cliente guardado con ID: " + clienteGuardado.getId(), "Exito", JOptionPane.INFORMATION_MESSAGE);

            LimpiarInputs();
            panelListarCliente.recargarDatos();

        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Validacion", JOptionPane.WARNING_MESSAGE);

        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage(), "Error de persistencia", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonGuardarClienteActionPerformed

    private void LimpiarInputs() {
        inputNombre.setText("");
        inputDni.setText("");
        inputDni.setValue(null);
        inputTelefono.setText("");
        inputTelefono.setValue(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JButton botonGuardarCliente;
    private javax.swing.JLabel clienteSiluetaImg;
    private javax.swing.JFormattedTextField inputDni;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JFormattedTextField inputTelefono;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlAgregarCliente;
    // End of variables declaration//GEN-END:variables

}
