/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.reserva;

/**
 *
 * @author LoloColombo
 */
public class PanelActualizarReserva extends javax.swing.JPanel {

    /**
     * Creates new form PanelActualizarReserva
     */
    public PanelActualizarReserva() {
        initComponents();
        ConfigurarGrupoBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTipoLavado = new javax.swing.ButtonGroup();
        pnlActualizarReserva = new javax.swing.JPanel();
        reservaSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNuevoLavado = new javax.swing.JLabel();
        separatorIDReserva = new javax.swing.JSeparator();
        lblReservaId = new javax.swing.JLabel();
        botonActualizarReserva = new javax.swing.JButton();
        bPremium = new javax.swing.JRadioButton();
        bStandard = new javax.swing.JRadioButton();
        bDeluxe = new javax.swing.JRadioButton();
        lblNuevoTurno = new javax.swing.JLabel();
        separatorTurno = new javax.swing.JSeparator();
        lblNuevaPatente = new javax.swing.JLabel();
        separatorPatente = new javax.swing.JSeparator();
        labelNuevoDni = new javax.swing.JLabel();
        separatorDni = new javax.swing.JSeparator();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        pnlActualizarReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlActualizarReserva.setForeground(new java.awt.Color(255, 255, 255));
        pnlActualizarReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservaSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FotoReserva.png"))); // NOI18N
        pnlActualizarReserva.add(reservaSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 200, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlActualizarReserva.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlActualizarReserva.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("ACTUALIZAR RESERVA");
        pnlActualizarReserva.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 280, 30));

        lblNuevoLavado.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoLavado.setText("NUEVO TIPO LAVADO");
        pnlActualizarReserva.add(lblNuevoLavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        separatorIDReserva.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarReserva.add(separatorIDReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 10));

        lblReservaId.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblReservaId.setText("ID DE RESERVA");
        pnlActualizarReserva.add(lblReservaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        botonActualizarReserva.setBackground(new java.awt.Color(0, 134, 190));
        botonActualizarReserva.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonActualizarReserva.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarReserva.setText("Guardar");
        botonActualizarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlActualizarReserva.add(botonActualizarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        bPremium.setText("PREMIUM");
        bPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPremiumActionPerformed(evt);
            }
        });
        pnlActualizarReserva.add(bPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        bStandard.setText("STANDARD");
        pnlActualizarReserva.add(bStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        bDeluxe.setText("DELUXE");
        bDeluxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeluxeActionPerformed(evt);
            }
        });
        pnlActualizarReserva.add(bDeluxe, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        lblNuevoTurno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoTurno.setText("NUEVO TURNO");
        pnlActualizarReserva.add(lblNuevoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        separatorTurno.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarReserva.add(separatorTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 340, 10));

        lblNuevaPatente.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevaPatente.setText("NUEVA PATENTE");
        pnlActualizarReserva.add(lblNuevaPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        separatorPatente.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarReserva.add(separatorPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 340, 10));

        labelNuevoDni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelNuevoDni.setText("NUEVO DNI");
        pnlActualizarReserva.add(labelNuevoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        separatorDni.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarReserva.add(separatorDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, 10));

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU###UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarReserva.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, -1));

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        pnlActualizarReserva.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, -1));

        try {
            jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarReserva.add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 340, -1));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        pnlActualizarReserva.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPremiumActionPerformed

    private void bDeluxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeluxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDeluxeActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed
    private void ConfigurarGrupoBotones(){
        
        GroupTipoLavado.add(bDeluxe);
        GroupTipoLavado.add(bPremium);
        GroupTipoLavado.add(bStandard);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.ButtonGroup GroupTipoLavado;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JRadioButton bDeluxe;
    private javax.swing.JRadioButton bPremium;
    private javax.swing.JRadioButton bStandard;
    private javax.swing.JButton botonActualizarReserva;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JLabel labelNuevoDni;
    private javax.swing.JLabel lblNuevaPatente;
    private javax.swing.JLabel lblNuevoLavado;
    private javax.swing.JLabel lblNuevoTurno;
    private javax.swing.JLabel lblReservaId;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlActualizarReserva;
    private javax.swing.JLabel reservaSiluetaImg;
    private javax.swing.JSeparator separatorDni;
    private javax.swing.JSeparator separatorIDReserva;
    private javax.swing.JSeparator separatorPatente;
    private javax.swing.JSeparator separatorTurno;
    // End of variables declaration//GEN-END:variables
}
