/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.reserva;

import com.idraGroup.lavadero.controller.ReservaController;
import com.idraGroup.lavadero.model.Reserva;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
/**
 *
 * @author LoloColombo
 */
public class PanelListarReserva extends javax.swing.JPanel {


    private final ReservaController reservaController;
    private static final DateTimeFormatter UI_FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    public PanelListarReserva(ReservaController reservaController) {
        this.reservaController = reservaController;
        initComponents();
        cargarReservas();
    }
/**
 * cargarReservas.

 */

    public void cargarReservas() {
       
        DefaultTableModel model = (DefaultTableModel) tblReservas.getModel();
     
        model.setRowCount(0); 

        try {
           
            List<Reserva> listaReservas = reservaController.listarReservas();

            for (Reserva reserva : listaReservas) {
             String turnoFormateado = reserva.getTurno().format(UI_FORMATTER);
                model.addRow(new Object[]{
                    reserva.getId(),
                    reserva.getAuto().getPatente(),
                    reserva.getCliente().getDni(),
                    turnoFormateado,
                    reserva.getTipoLavado(),
                    reserva.getPrecio()
                });
            }
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al cargar las reservas desde la base de datos: " + e.getMessage(),
                    "Error de Persistencia",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
/**
 * recargarDatos.

 */
    
    public void recargarDatos(){
        cargarReservas();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlListarReserva = new javax.swing.JPanel();
        reservaSiluetaImg3 = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();

        pnlListarReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlListarReserva.setForeground(new java.awt.Color(255, 255, 255));
        pnlListarReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservaSiluetaImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FotoReserva.png"))); // NOI18N
        pnlListarReserva.add(reservaSiluetaImg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 200, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlListarReserva.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 200, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlListarReserva.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("LISTA DE RESERVAS");
        pnlListarReserva.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 190, 30));

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PATENTE", "DNI", "TURNO", "TIPO LAVADO", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };
/**
 * isCellEditable.
 * @param rowIndex int.
 * @param columnIndex int.

 * @return boolean.
 */

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblReservas);

        pnlListarReserva.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 550, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlListarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlListarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlListarReserva;
    private javax.swing.JLabel reservaSiluetaImg3;
    private javax.swing.JTable tblReservas;
    // End of variables declaration//GEN-END:variables
}
