/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.reserva;

/**
 *
 * @author LoloColombo
 */
public class PanelEliminarReserva extends javax.swing.JPanel {

    /**
     * Creates new form PanelEliminarReserva
     */
    public PanelEliminarReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEliminarReserva = new javax.swing.JPanel();
        reservaSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblReservaId = new javax.swing.JLabel();
        inputReservaId = new javax.swing.JTextField();
        separatorReservaId = new javax.swing.JSeparator();
        botonEliminarReserva = new javax.swing.JButton();

        pnlEliminarReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlEliminarReserva.setForeground(new java.awt.Color(255, 255, 255));
        pnlEliminarReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservaSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FotoReserva.png"))); // NOI18N
        pnlEliminarReserva.add(reservaSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 200, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlEliminarReserva.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlEliminarReserva.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("ELIMINAR RESERVA");
        pnlEliminarReserva.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 30));

        lblReservaId.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblReservaId.setText("ID RESERVA");
        pnlEliminarReserva.add(lblReservaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        inputReservaId.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputReservaId.setForeground(new java.awt.Color(204, 204, 204));
        inputReservaId.setText("Ingrese el ID de la reserva a eliminar");
        inputReservaId.setBorder(null);
        inputReservaId.setCaretColor(new java.awt.Color(204, 204, 204));
        inputReservaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputReservaIdActionPerformed(evt);
            }
        });
        pnlEliminarReserva.add(inputReservaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 390, -1));

        separatorReservaId.setForeground(new java.awt.Color(0, 0, 0));
        pnlEliminarReserva.add(separatorReservaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, -1));

        botonEliminarReserva.setBackground(new java.awt.Color(153, 0, 0));
        botonEliminarReserva.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonEliminarReserva.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminarReserva.setText("Eliminar");
        botonEliminarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEliminarReserva.add(botonEliminarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEliminarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlEliminarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputReservaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputReservaIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputReservaIdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JButton botonEliminarReserva;
    private javax.swing.JTextField inputReservaId;
    private javax.swing.JLabel lblReservaId;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlEliminarReserva;
    private javax.swing.JLabel reservaSiluetaImg;
    private javax.swing.JSeparator separatorReservaId;
    // End of variables declaration//GEN-END:variables
}
