/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.reserva;

/**
 *
 * @author LoloColombo
 */
public class PanelAgregarReserva extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgregarReserva
     */
    public PanelAgregarReserva() {
        initComponents();
        ConfigurarGrupoBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTipoLavado = new javax.swing.ButtonGroup();
        pnlAgregarReserva = new javax.swing.JPanel();
        reservaSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblLavado = new javax.swing.JLabel();
        separatorDni = new javax.swing.JSeparator();
        lblDni = new javax.swing.JLabel();
        botonGuardarReserva = new javax.swing.JButton();
        bPremium = new javax.swing.JRadioButton();
        bStandard = new javax.swing.JRadioButton();
        bDeluxe = new javax.swing.JRadioButton();
        lblTurno = new javax.swing.JLabel();
        separatorTurno = new javax.swing.JSeparator();
        lblPatente = new javax.swing.JLabel();
        separatorPatente = new javax.swing.JSeparator();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        pnlAgregarReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlAgregarReserva.setForeground(new java.awt.Color(255, 255, 255));
        pnlAgregarReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservaSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FotoReserva.png"))); // NOI18N
        pnlAgregarReserva.add(reservaSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 200, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlAgregarReserva.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlAgregarReserva.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("REGISTRAR RESERVA");
        pnlAgregarReserva.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 280, 30));

        lblLavado.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblLavado.setText("TIPO LAVADO");
        pnlAgregarReserva.add(lblLavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        separatorDni.setForeground(new java.awt.Color(0, 0, 0));
        pnlAgregarReserva.add(separatorDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 340, 10));

        lblDni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblDni.setText("DNI");
        pnlAgregarReserva.add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        botonGuardarReserva.setBackground(new java.awt.Color(0, 134, 190));
        botonGuardarReserva.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonGuardarReserva.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarReserva.setText("Guardar");
        botonGuardarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAgregarReserva.add(botonGuardarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        bPremium.setText("PREMIUM");
        bPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPremiumActionPerformed(evt);
            }
        });
        pnlAgregarReserva.add(bPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        bStandard.setText("STANDARD");
        pnlAgregarReserva.add(bStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        bDeluxe.setText("DELUXE");
        bDeluxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeluxeActionPerformed(evt);
            }
        });
        pnlAgregarReserva.add(bDeluxe, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

        lblTurno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblTurno.setText("TURNO");
        pnlAgregarReserva.add(lblTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        separatorTurno.setForeground(new java.awt.Color(0, 0, 0));
        pnlAgregarReserva.add(separatorTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, 10));

        lblPatente.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblPatente.setText("PATENTE");
        pnlAgregarReserva.add(lblPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        separatorPatente.setForeground(new java.awt.Color(0, 0, 0));
        pnlAgregarReserva.add(separatorPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 340, 10));

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        pnlAgregarReserva.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, -1));

        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlAgregarReserva.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 340, -1));

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlAgregarReserva.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAgregarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlAgregarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPremiumActionPerformed

    private void bDeluxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeluxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDeluxeActionPerformed
    private void ConfigurarGrupoBotones(){
        
        GroupTipoLavado.add(bDeluxe);
        GroupTipoLavado.add(bPremium);
        GroupTipoLavado.add(bStandard);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.ButtonGroup GroupTipoLavado;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JRadioButton bDeluxe;
    private javax.swing.JRadioButton bPremium;
    private javax.swing.JRadioButton bStandard;
    private javax.swing.JButton botonGuardarReserva;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblLavado;
    private javax.swing.JLabel lblPatente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JPanel pnlAgregarReserva;
    private javax.swing.JLabel reservaSiluetaImg;
    private javax.swing.JSeparator separatorDni;
    private javax.swing.JSeparator separatorPatente;
    private javax.swing.JSeparator separatorTurno;
    // End of variables declaration//GEN-END:variables
}
