/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.reserva;

import com.idraGroup.lavadero.controller.ReservaController;
import com.idraGroup.lavadero.model.Reserva;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;
import javax.swing.text.DefaultFormatterFactory;

/**
 *
 * @author LoloColombo
 */
public class PanelActualizarReserva extends javax.swing.JPanel {

    private final ReservaController reservaController;
    private final PanelListarReserva panelListarReserva;

    private static final DateTimeFormatter UI_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    public PanelActualizarReserva(ReservaController reservaController, PanelListarReserva panelListarReserva) {
        this.reservaController = reservaController;
        this.panelListarReserva = panelListarReserva;
        initComponents();
        ConfigurarGrupoBotones();
        configurarInputTurno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTipoLavado = new javax.swing.ButtonGroup();
        pnlActualizarReserva = new javax.swing.JPanel();
        reservaSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNuevoLavado = new javax.swing.JLabel();
        lblReservaId = new javax.swing.JLabel();
        botonActualizarReserva = new javax.swing.JButton();
        bPremium = new javax.swing.JRadioButton();
        bStandard = new javax.swing.JRadioButton();
        bDeluxe = new javax.swing.JRadioButton();
        lblNuevoTurno = new javax.swing.JLabel();
        lblNuevaPatente = new javax.swing.JLabel();
        labelNuevoDni = new javax.swing.JLabel();
        InputNuevaPatente = new javax.swing.JFormattedTextField();
        InputNuevoTurno = new javax.swing.JFormattedTextField();
        InputNuevoDni = new javax.swing.JFormattedTextField();
        inputIdReserva = new javax.swing.JFormattedTextField();

        pnlActualizarReserva.setBackground(new java.awt.Color(255, 255, 255));
        pnlActualizarReserva.setForeground(new java.awt.Color(255, 255, 255));
        pnlActualizarReserva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservaSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FotoReserva.png"))); // NOI18N
        pnlActualizarReserva.add(reservaSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 200, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlActualizarReserva.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlActualizarReserva.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("ACTUALIZAR RESERVA");
        pnlActualizarReserva.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 280, 30));

        lblNuevoLavado.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoLavado.setText("NUEVO TIPO LAVADO");
        pnlActualizarReserva.add(lblNuevoLavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        lblReservaId.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblReservaId.setText("ID DE RESERVA");
        pnlActualizarReserva.add(lblReservaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        botonActualizarReserva.setBackground(new java.awt.Color(0, 134, 190));
        botonActualizarReserva.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonActualizarReserva.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarReserva.setText("Guardar");
        botonActualizarReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizarReserva.addActionListener(new java.awt.event.ActionListener() {
/**
 * actionPerformed.
 * @param evt java.awt.event.ActionEvent.

 */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarReservaActionPerformed(evt);
            }
        });
        pnlActualizarReserva.add(botonActualizarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        bPremium.setText("PREMIUM");
        bPremium.addActionListener(new java.awt.event.ActionListener() {
/**
 * actionPerformed.
 * @param evt java.awt.event.ActionEvent.

 */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPremiumActionPerformed(evt);
            }
        });
        pnlActualizarReserva.add(bPremium, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        bStandard.setText("STANDARD");
        pnlActualizarReserva.add(bStandard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        bDeluxe.setText("DELUXE");
        bDeluxe.addActionListener(new java.awt.event.ActionListener() {
/**
 * actionPerformed.
 * @param evt java.awt.event.ActionEvent.

 */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeluxeActionPerformed(evt);
            }
        });
        pnlActualizarReserva.add(bDeluxe, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        lblNuevoTurno.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoTurno.setText("NUEVO TURNO");
        pnlActualizarReserva.add(lblNuevoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        lblNuevaPatente.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevaPatente.setText("NUEVA PATENTE");
        pnlActualizarReserva.add(lblNuevaPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        labelNuevoDni.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelNuevoDni.setText("NUEVO DNI");
        pnlActualizarReserva.add(labelNuevoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        try {
            InputNuevaPatente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU###UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarReserva.add(InputNuevaPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, -1));

        InputNuevoTurno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        pnlActualizarReserva.add(InputNuevoTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 340, -1));

        try {
            InputNuevoDni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarReserva.add(InputNuevoDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 340, -1));

        inputIdReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        inputIdReserva.addActionListener(new java.awt.event.ActionListener() {
/**
 * actionPerformed.
 * @param evt java.awt.event.ActionEvent.

 */
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdReservaActionPerformed(evt);
            }
        });
        pnlActualizarReserva.add(inputIdReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bPremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPremiumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPremiumActionPerformed

    private void bDeluxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeluxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bDeluxeActionPerformed

    private void inputIdReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdReservaActionPerformed

    private void botonActualizarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarReservaActionPerformed
       String idStr = inputIdReserva.getText().trim();
        String nuevoDniStr = InputNuevoDni.getText().trim();
        String nuevaPatenteStr = InputNuevaPatente.getText().trim().toUpperCase();
        String nuevoTurnoStr = InputNuevoTurno.getText().trim();
        String nuevoTipoLavado = obtenerTipoSeleccionado();
        
        if (idStr.isEmpty()) {
             JOptionPane.showMessageDialog(this, "Debe ingresar el ID de la reserva a actualizar.", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            if (nuevoDniStr.isEmpty() || nuevaPatenteStr.isEmpty() || nuevoTurnoStr.isEmpty() || nuevoTipoLavado == null) {
                throw new IllegalArgumentException("Todos los campos (DNI, Patente, Turno, Tipo Lavado) son obligatorios.");
            }
            
            Integer idReserva = Integer.parseInt(idStr);
       
            if (reservaController.buscarPorId(idReserva).isEmpty()) {
                 throw new IllegalArgumentException("No se encontró ninguna reserva con ID: " + idReserva + ". No se puede actualizar.");
            }
            
            
            Reserva reservaModificada = reservaController.actualizarReserva(
                idReserva,
                nuevoDniStr,
                nuevaPatenteStr,
                nuevoTurnoStr,
                nuevoTipoLavado
            );
   
            JOptionPane.showMessageDialog(this,
                    "Reserva N°" + reservaModificada.getId() + " actualizada exitosamente.",
                    "Éxito al Actualizar",
                    JOptionPane.INFORMATION_MESSAGE);

            limpiarInputs();
            panelListarReserva.recargarDatos(); 

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error de Formato", JOptionPane.WARNING_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error de Validación", JOptionPane.WARNING_MESSAGE);
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, 
                    "Error al intentar actualizar la reserva: " + e.getMessage(), 
                    "Error de Persistencia", 
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_botonActualizarReservaActionPerformed
    private void ConfigurarGrupoBotones() {

        GroupTipoLavado.add(bDeluxe);
        GroupTipoLavado.add(bPremium);
        GroupTipoLavado.add(bStandard);

    }

    private void configurarInputTurno() {
        try {

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            DateTimeFormatter controllerFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

            dateFormat.setLenient(false);
            DateFormatter dateFormatter = new DateFormatter(dateFormat);
            InputNuevoTurno.setFormatterFactory(new DefaultFormatterFactory(dateFormatter));

            InputNuevoTurno.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

            String horaActual = LocalDateTime.now().format(controllerFormatter);
            InputNuevoTurno.setText(horaActual);

        } catch (IllegalArgumentException e) {
            System.err.println("Error al configurar el formato de fecha: " + e.getMessage());
        }
    }

    private void limpiarInputs() {
        inputIdReserva.setText("");
        InputNuevoDni.setText("");
        InputNuevaPatente.setText("");
        inputIdReserva.setValue(null);
        InputNuevoDni.setValue(null);
        InputNuevaPatente.setValue(null);
        GroupTipoLavado.clearSelection();

    }
    
    private String obtenerTipoSeleccionado() {
        if (bStandard.isSelected()) {
            return "STANDARD";
        }
        if (bPremium.isSelected()) {
            return "PREMIUM";
        }
        if (bDeluxe.isSelected()) {
            return "DELUXE";
        }
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.ButtonGroup GroupTipoLavado;
    private javax.swing.JFormattedTextField InputNuevaPatente;
    private javax.swing.JFormattedTextField InputNuevoDni;
    private javax.swing.JFormattedTextField InputNuevoTurno;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JRadioButton bDeluxe;
    private javax.swing.JRadioButton bPremium;
    private javax.swing.JRadioButton bStandard;
    private javax.swing.JButton botonActualizarReserva;
    private javax.swing.JFormattedTextField inputIdReserva;
    private javax.swing.JLabel labelNuevoDni;
    private javax.swing.JLabel lblNuevaPatente;
    private javax.swing.JLabel lblNuevoLavado;
    private javax.swing.JLabel lblNuevoTurno;
    private javax.swing.JLabel lblReservaId;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlActualizarReserva;
    private javax.swing.JLabel reservaSiluetaImg;
    // End of variables declaration//GEN-END:variables
}
