/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.reserva;

/**
 *
 * @author LoloColombo
 */
public class PanelEliminarReserva extends javax.swing.JPanel {

    /**
     * Creates new form PanelEliminarReserva
     */
    public PanelEliminarReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgClienteCrear2 = new javax.swing.JPanel();
        clienteSiluetaImg2 = new javax.swing.JLabel();
        CiudadImg2 = new javax.swing.JLabel();
        LogoImg2 = new javax.swing.JLabel();
        clienteCrearTitulo2 = new javax.swing.JLabel();
        labelNombre2 = new javax.swing.JLabel();
        inputNombre2 = new javax.swing.JTextField();
        separatorDni2 = new javax.swing.JSeparator();
        botonGuardarCliente2 = new javax.swing.JButton();

        bgClienteCrear2.setBackground(new java.awt.Color(255, 255, 255));
        bgClienteCrear2.setForeground(new java.awt.Color(255, 255, 255));
        bgClienteCrear2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clienteSiluetaImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FotoReserva.png"))); // NOI18N
        bgClienteCrear2.add(clienteSiluetaImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 200, 430));

        CiudadImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        bgClienteCrear2.add(CiudadImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        bgClienteCrear2.add(LogoImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 40));

        clienteCrearTitulo2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        clienteCrearTitulo2.setText("ELIMINAR RESERVA");
        bgClienteCrear2.add(clienteCrearTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 280, 30));

        labelNombre2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        labelNombre2.setText("ID RESERVA");
        bgClienteCrear2.add(labelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        inputNombre2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        inputNombre2.setForeground(new java.awt.Color(204, 204, 204));
        inputNombre2.setText("Ingrese el ID de la reserva a eliminar");
        inputNombre2.setBorder(null);
        inputNombre2.setCaretColor(new java.awt.Color(204, 204, 204));
        inputNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombre2ActionPerformed(evt);
            }
        });
        bgClienteCrear2.add(inputNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 390, -1));

        separatorDni2.setForeground(new java.awt.Color(0, 0, 0));
        bgClienteCrear2.add(separatorDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, -1));

        botonGuardarCliente2.setBackground(new java.awt.Color(153, 0, 0));
        botonGuardarCliente2.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonGuardarCliente2.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarCliente2.setText("Eliminar");
        botonGuardarCliente2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bgClienteCrear2.add(botonGuardarCliente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgClienteCrear2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgClienteCrear2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombre2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg2;
    private javax.swing.JLabel LogoImg2;
    private javax.swing.JPanel bgClienteCrear2;
    private javax.swing.JButton botonGuardarCliente2;
    private javax.swing.JLabel clienteCrearTitulo2;
    private javax.swing.JLabel clienteSiluetaImg2;
    private javax.swing.JTextField inputNombre2;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JSeparator separatorDni2;
    // End of variables declaration//GEN-END:variables
}
