/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.reserva;

import com.idraGroup.lavadero.controller.ReservaController;

/**
 *
 * @author LoloColombo
 */
public class ReservaView extends javax.swing.JPanel {

    /**
     * Creates new form ReservaView
     */
    private final ReservaController reservaController;
    private final PanelListarReserva panelListarReserva;

    public ReservaView(ReservaController reservaController) {
        this.reservaController = reservaController;
        this.panelListarReserva = new PanelListarReserva(reservaController);
        initComponents();

        PanelAgregarReserva panelAgregarReserva = new PanelAgregarReserva(reservaController, panelListarReserva);
        tabbedPaneReserva.add("CREAR", panelAgregarReserva);

        PanelActualizarReserva panelActualizarReserva = new PanelActualizarReserva(reservaController, panelListarReserva);
        tabbedPaneReserva.add("ACTUALIZAR", panelActualizarReserva);

        PanelEliminarReserva panelEliminarReserva = new PanelEliminarReserva(reservaController, panelListarReserva);
        tabbedPaneReserva.add("ELIMINAR", panelEliminarReserva);

        tabbedPaneReserva.add("LISTAR", panelListarReserva);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPaneReserva = new com.idraGroup.lavadero.view.ravenTabbed.TabbedPaneCustom();

        setBackground(new java.awt.Color(255, 255, 255));

        tabbedPaneReserva.setSelectedColor(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneReserva, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPaneReserva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.idraGroup.lavadero.view.ravenTabbed.TabbedPaneCustom tabbedPaneReserva;
    // End of variables declaration//GEN-END:variables
}
