/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.Auto;

/**
 *
 * @author LoloColombo
 */
public class PanelAgregarAuto extends javax.swing.JPanel {

    /**
     * Creates new form PanelAgregarAuto
     */
    public PanelAgregarAuto() {
        initComponents();
        ConfigurarGrupoBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTipoAuto = new javax.swing.ButtonGroup();
        pnlCrearAuto = new javax.swing.JPanel();
        autoSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTipoAuto = new javax.swing.JLabel();
        separatorPatente = new javax.swing.JSeparator();
        lblPatente = new javax.swing.JLabel();
        botonGuardarAuto = new javax.swing.JButton();
        bCamioneta = new javax.swing.JRadioButton();
        bSedan = new javax.swing.JRadioButton();
        bSUV = new javax.swing.JRadioButton();
        bFurgoneta = new javax.swing.JRadioButton();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();

        pnlCrearAuto.setBackground(new java.awt.Color(255, 255, 255));
        pnlCrearAuto.setForeground(new java.awt.Color(255, 255, 255));
        pnlCrearAuto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        autoSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fotoAuto - copia.png"))); // NOI18N
        pnlCrearAuto.add(autoSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 250, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlCrearAuto.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlCrearAuto.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("REGISTRAR AUTO");
        pnlCrearAuto.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, 30));

        lblTipoAuto.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblTipoAuto.setText("TIPO");
        pnlCrearAuto.add(lblTipoAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        separatorPatente.setForeground(new java.awt.Color(0, 0, 0));
        pnlCrearAuto.add(separatorPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 340, -1));

        lblPatente.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblPatente.setText("PATENTE");
        pnlCrearAuto.add(lblPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        botonGuardarAuto.setBackground(new java.awt.Color(0, 134, 190));
        botonGuardarAuto.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonGuardarAuto.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardarAuto.setText("Guardar");
        botonGuardarAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlCrearAuto.add(botonGuardarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        bCamioneta.setText("Camioneta");
        bCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCamionetaActionPerformed(evt);
            }
        });
        pnlCrearAuto.add(bCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        bSedan.setText("Sedan");
        pnlCrearAuto.add(bSedan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        bSUV.setText("SUV");
        pnlCrearAuto.add(bSUV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        bFurgoneta.setText("Furgoneta");
        bFurgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFurgonetaActionPerformed(evt);
            }
        });
        pnlCrearAuto.add(bFurgoneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU###UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlCrearAuto.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCrearAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlCrearAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCamionetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCamionetaActionPerformed

    private void bFurgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFurgonetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFurgonetaActionPerformed

    private void ConfigurarGrupoBotones(){
        
        GroupTipoAuto.add(bCamioneta);
        GroupTipoAuto.add(bSedan);
        GroupTipoAuto.add(bSUV);
        GroupTipoAuto.add(bFurgoneta);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.ButtonGroup GroupTipoAuto;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JLabel autoSiluetaImg;
    private javax.swing.JRadioButton bCamioneta;
    private javax.swing.JRadioButton bFurgoneta;
    private javax.swing.JRadioButton bSUV;
    private javax.swing.JRadioButton bSedan;
    private javax.swing.JButton botonGuardarAuto;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel lblPatente;
    private javax.swing.JLabel lblTipoAuto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCrearAuto;
    private javax.swing.JSeparator separatorPatente;
    // End of variables declaration//GEN-END:variables
}
