/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.idraGroup.lavadero.view.Auto;

/**
 *
 * @author LoloColombo
 */
public class PanelActualizarAuto extends javax.swing.JPanel {

    /**
     * Creates new form PanelActualizarAuto
     */
    public PanelActualizarAuto() {
        initComponents();
        ConfigurarGrupoBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GroupTipoAuto = new javax.swing.ButtonGroup();
        pnlActualizarAuto = new javax.swing.JPanel();
        autoSiluetaImg = new javax.swing.JLabel();
        CiudadImg = new javax.swing.JLabel();
        LogoImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblNuevoTipo = new javax.swing.JLabel();
        separatorPatenteActual = new javax.swing.JSeparator();
        lblPatenteActual = new javax.swing.JLabel();
        botonActualizarAuto = new javax.swing.JButton();
        bCamioneta = new javax.swing.JRadioButton();
        bSedan = new javax.swing.JRadioButton();
        bSUV = new javax.swing.JRadioButton();
        bFurgoneta = new javax.swing.JRadioButton();
        lblNuevaPatente = new javax.swing.JLabel();
        separatorNuevaPatente = new javax.swing.JSeparator();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();

        pnlActualizarAuto.setBackground(new java.awt.Color(255, 255, 255));
        pnlActualizarAuto.setForeground(new java.awt.Color(255, 255, 255));
        pnlActualizarAuto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        autoSiluetaImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fotoAuto - copia.png"))); // NOI18N
        pnlActualizarAuto.add(autoSiluetaImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 250, 430));

        CiudadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        pnlActualizarAuto.add(CiudadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 430));

        LogoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoLavadero.png"))); // NOI18N
        pnlActualizarAuto.add(LogoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 80, 40));

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblTitulo.setText("ACTUALIZAR AUTO");
        pnlActualizarAuto.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 280, 30));

        lblNuevoTipo.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevoTipo.setText("NUEVO TIPO");
        pnlActualizarAuto.add(lblNuevoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        separatorPatenteActual.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarAuto.add(separatorPatenteActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 340, 10));

        lblPatenteActual.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblPatenteActual.setText("PATENTE ACTUAL");
        pnlActualizarAuto.add(lblPatenteActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        botonActualizarAuto.setBackground(new java.awt.Color(0, 134, 190));
        botonActualizarAuto.setFont(new java.awt.Font("Roboto Condensed Black", 0, 18)); // NOI18N
        botonActualizarAuto.setForeground(new java.awt.Color(255, 255, 255));
        botonActualizarAuto.setText("Guardar");
        botonActualizarAuto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlActualizarAuto.add(botonActualizarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, 40));

        bCamioneta.setText("Camioneta");
        bCamioneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCamionetaActionPerformed(evt);
            }
        });
        pnlActualizarAuto.add(bCamioneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        bSedan.setText("Sedan");
        bSedan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSedanActionPerformed(evt);
            }
        });
        pnlActualizarAuto.add(bSedan, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        bSUV.setText("SUV");
        pnlActualizarAuto.add(bSUV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        bFurgoneta.setText("Furgoneta");
        bFurgoneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFurgonetaActionPerformed(evt);
            }
        });
        pnlActualizarAuto.add(bFurgoneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        lblNuevaPatente.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        lblNuevaPatente.setText("NUEVA PATENTE");
        pnlActualizarAuto.add(lblNuevaPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        separatorNuevaPatente.setForeground(new java.awt.Color(0, 0, 0));
        pnlActualizarAuto.add(separatorNuevaPatente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 340, 10));

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarAuto.add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, -1));

        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UU###UU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlActualizarAuto.add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 340, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlActualizarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlActualizarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCamionetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCamionetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCamionetaActionPerformed

    private void bFurgonetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFurgonetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFurgonetaActionPerformed

    private void bSedanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSedanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSedanActionPerformed
    private void ConfigurarGrupoBotones(){
        
        GroupTipoAuto.add(bCamioneta);
        GroupTipoAuto.add(bSedan);
        GroupTipoAuto.add(bSUV);
        GroupTipoAuto.add(bFurgoneta);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CiudadImg;
    private javax.swing.ButtonGroup GroupTipoAuto;
    private javax.swing.JLabel LogoImg;
    private javax.swing.JLabel autoSiluetaImg;
    private javax.swing.JRadioButton bCamioneta;
    private javax.swing.JRadioButton bFurgoneta;
    private javax.swing.JRadioButton bSUV;
    private javax.swing.JRadioButton bSedan;
    private javax.swing.JButton botonActualizarAuto;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel lblNuevaPatente;
    private javax.swing.JLabel lblNuevoTipo;
    private javax.swing.JLabel lblPatenteActual;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlActualizarAuto;
    private javax.swing.JSeparator separatorNuevaPatente;
    private javax.swing.JSeparator separatorPatenteActual;
    // End of variables declaration//GEN-END:variables
}
